services:
  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - ./.env
    environment:
      USERNAME: ${REDIS_USERNAME}
      PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --appendonly yes
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge